//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exp_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeviceTbl()
        {
            this.EventDevices = new HashSet<EventDevice>();
        }
    
        public int ID { get; set; }
        public string DeviceID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> UserAssigned { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventDevice> EventDevices { get; set; }
    }
}
