//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exp_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventDevice
    {
        public int ID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public Nullable<int> isActive { get; set; }
    
        public virtual DeviceTbl DeviceTbl { get; set; }
        public virtual Event Event { get; set; }
    }
}
