//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exp_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MetricElement()
        {
            this.EventFeedbacks = new HashSet<EventFeedback>();
        }
    
        public int ID { get; set; }
        public Nullable<int> EventMetricID { get; set; }
        public Nullable<int> EventID { get; set; }
        public string Title { get; set; }
        public string Icon { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual Event Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventFeedback> EventFeedbacks { get; set; }
        public virtual EventMetric EventMetric { get; set; }
    }
}
