// Template: Base Controller (ApiControllerBase.t4) version 1.1

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using iedge.exp_api.Models;

// Do not modify this file. This code was generated by RAML Web Api 2 Scaffolder

namespace iedge.exp_api
{
    [RoutePrefix("event")]
    public partial class EventController : ApiController
    {


        /// <summary>
		/// Entity representing a event. Get event configuration.
		/// </summary>
		/// <param name="deviceid">This is the device id</param>
        [HttpGet]
        [Route("")]
        public virtual IHttpActionResult GetBase([FromUri] string deviceid)
        {
            // Do not modify this code
            return  ((IEventController)this).Get(deviceid);
        }
    }
}
