// Template: Models (ApiModel.t4) version 1.1

// This code was generated by RAML Web Api 2 Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace iedge.exp_api.Models
{
    public partial class Event
    {
        
		[JsonProperty("settings")]
        public Settings Settings { get; set; }
		[JsonProperty("metrics")]
        public IList<string> Metrics { get; set; }
    } // end class

} // end Models namespace
