// Template: Models (ApiModel.t4) version 1.1

// This code was generated by RAML Web Api 2 Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace iedge.exp_api.Models
{
	public partial class Eventfeedback
	{
		
		[JsonProperty("eventid")]
		public string Eventid { get; set; }
		[JsonProperty("feedbackval")]
		public string Feedbackval { get; set; }
		[JsonProperty("email")]
		public string Email { get; set; }
		[JsonProperty("fullname")]
		public string Fullname { get; set; }
		[JsonProperty("phone")]
		public string Phone { get; set; }

		[JsonProperty("comment")]
		public string Comment { get; set; }

		[JsonProperty("gender")]
		public string Gender { get; set; }

		[JsonProperty("dateadded")]
		public string DateAdded { get; set; }

	} // end class

} // end Models namespace
