// Template: Base Controller (ApiControllerBase.t4) version 1.1

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using iedge.exp_api.Models;

// Do not modify this file. This code was generated by RAML Web Api 2 Scaffolder

namespace iedge.exp_api
{
    [RoutePrefix("feedback")]
    public partial class FeedbackController : ApiController
    {


        /// <summary>
		/// Entity representing a feedback. Post a feedback
		/// </summary>
		/// <param name="feedbackpostrequestcontent"></param>
		/// <param name="deviceid">This is the device id</param>
		/// <param name="eventid">This is the event id</param>
        [HttpPost]
        [Route("")]
        public virtual IHttpActionResult PostBase(Models.FeedbackPostRequestContent feedbackpostrequestcontent, [FromUri] string deviceid, [FromUri] string eventid)
        {
            // Do not modify this code
            return ((IFeedbackController)this).Post(feedbackpostrequestcontent, deviceid, eventid);
        }

        [HttpPost]
        [Route("")]
        public virtual IHttpActionResult PostBase(Models.FeedbackPostRequestContent feedbackpostrequestcontent)
        {
            // Do not modify this code
            return ((IFeedbackController)this).Post(feedbackpostrequestcontent);
        }
    }
}
