// Template: Models (ApiModel.t4) version 1.1

// This code was generated by RAML Web Api 2 Scaffolder

using System;
using System.Collections.Generic;
using iedge.exp_api.Model;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace iedge.exp_api.Models
{
    public partial class FeedbackPostRequestContent
    {
        
		[JsonProperty("eventfeedback")]
        public Eventfeedback Eventfeedback { get; set; }
		[JsonProperty("feedbacks")]
        public IList<FeedbackItem> Feedbacks { get; set; }
    } // end class

} // end Models namespace
